FROM golang:1.14-alpine

ADD scripts/wait-for.sh /wait-for.sh

RUN apk --update --no-cache add git openssh mongodb gcc cyrus-sasl cyrus-sasl-dev musl-dev && \
    mkdir -p /oplogtoredis && \
    go get github.com/pilu/fresh

WORKDIR /oplogtoredis

CMD fresh
