FROM golang:1.17.0

# This dockerfile doesn't use alpine because race detection doesn't work.
# https://github.com/golang/go/issues/14481

WORKDIR /oplogtoredis

COPY main.go go.sum go.mod ./
COPY lib ./lib

RUN go build -o /bin/oplogtoredis -race && rm -rf $GOPATH

ENV PORT 8080
EXPOSE 8080
