FROM golang:1.12.9-alpine3.9

ADD scripts/wait-for.sh /wait-for.sh

RUN apk --update --no-cache add git openssh mongodb gcc cyrus-sasl cyrus-sasl-dev musl-dev && \
    mkdir -p /go/src/github.com/tulip/oplogtoredis && \
    go get github.com/pilu/fresh

WORKDIR /go/src/github.com/tulip/oplogtoredis

CMD fresh
