version: "3"
services:
  oplogtoredis:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    depends_on:
      - mongo
      - redis
    command:
      - /wait-for.sh
      - mongo:27017
      - '--'
      - /wait-for.sh
      - redis:6379
      - '--'
      - sh
      - -c
      - |
        fresh -c scripts/fresh-runner.conf
    environment:
      - OTR_MONGO_URL=mongodb://mongo/dev
      - OTR_REDIS_URL=redis://redis
      - OTR_LOG_DEBUG=true
    ports:
      - 9000:9000
    volumes:
      - ./scripts/wait-for.sh:/wait-for.sh
      - .:/oplogtoredis
  mongo:
    build:
      context: .
      dockerfile: ./Dockerfile.dev.mongo
    volumes:
      - './.data/mongo-data:/data/db'
  redis:
    image: redis:3.2.11
