FROM golang:1.12.9
# This dockerfile doesn't use alpine because race detection doesn't work.
# https://github.com/golang/go/issues/14481

RUN mkdir -p /go/src/github.com/tulip/oplogtoredis
WORKDIR /go/src/github.com/tulip/oplogtoredis

COPY vendor ./vendor
COPY lib ./lib
COPY main.go .
RUN go build -o app -race && mv ./app /bin/oplogtoredis

ENV PORT 8080
EXPOSE 8080
