FROM golang:1.17.0-alpine3.14

# Install gcc, musl-dev, and sasl, which are needed to build the cgo
# parts of mgo
RUN apk add --no-cache --update \
	gcc cyrus-sasl cyrus-sasl-dev musl-dev git

RUN echo 'http://dl-cdn.alpinelinux.org/alpine/v3.6/main' >> /etc/apk/repositories
RUN echo 'http://dl-cdn.alpinelinux.org/alpine/v3.6/community' >> /etc/apk/repositories
RUN apk update
RUN apk add mongodb=3.4.4-r0

WORKDIR /oplogtoredis

COPY main.go go.mod go.sum ./
COPY lib ./lib

RUN go build -o /bin/oplogtoredis

ADD scripts/wait-for.sh /wait-for.sh
ADD blackbox-tests/oplogtoredis-entry.sh /oplogtoredis-entry.sh
