version: "3"
services:
  test:
    build:
      context: ../..
      dockerfile: Dockerfile.integration
    depends_on:
      oplogtoredis:
        condition: service_started
      mongo:
        condition: service_healthy
      redis:
        condition: service_started
      redis-sentinel:
        condition: service_started
      redis-sentinel-master:
        condition: service_started
    command:
      - /wait-for.sh
      - --timeout=60
      - mongo:27017
      - '--'
      - /wait-for.sh
      - --timeout=60
      - redis:6379
      - '--'
      - /wait-for.sh
      - --timeout=120
      - redis-sentinel:26379
      - '--'
      - /integration/performance/entry.sh
    environment:
      - MONGO_URL=mongodb://mongo/tests
      - REDIS_URL=redis://redis-sentinel:26379,redis://redis

  oplogtoredis:
    build: ../..
    environment:
      - OTR_MONGO_URL=mongodb://mongo/tests
      - OTR_REDIS_URL=redis-sentinel://redis-sentinel:26379?sentinelMasterId=mymaster,redis://redis
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ../../scripts/wait-for.sh:/wait-for.sh
    command:
      - /wait-for.sh
      - --timeout=60
      - mongo:27017
      - '--'
      - /wait-for.sh
      - --timeout=60
      - redis:6379
      - '--'
      - /bin/oplogtoredis

  mongo:
    image: mongo:5.0.19
    command: "mongod --replSet myapp --port 27017"
    logging:
      driver: none
    healthcheck:
      test: test $$(echo "rs.initiate({_id:'myapp',members:[{_id:0,host:\"mongo:27017\"}]}).ok || rs.status().ok" | mongo --port 27017 --quiet) -eq 1
      interval: 10s
      start_period: 10s
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:6.0
    logging:
      driver: none

  redis-sentinel-master:
    image: redis:6.0
    environment:
      - REDIS_REPLICATION_MODE=master

  redis-sentinel:
    image: bitnami/redis-sentinel:latest
    environment:
      - REDIS_SENTINEL_MASTER=redis-sentinel-master


volumes:
  mongo_data:
