name: Setup ECR / Buildx
description: Composite action to setup requirements for ECR and buildx for docker pushes

inputs:
  registry-type:
    description: ECR Registry Type
    default: private
  role-to-assume:
    description: ECR Role to Assume
    required: true

outputs:
  ecr_registry:
    description: ECR Registry
    value: ${{ steps.login-ecr.outputs.registry }}

runs:
  using: "composite"
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ inputs.role-to-assume }}
        role-session-name: github-action-session
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        registry-type: ${{ inputs.registry_type }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@ecf95283f03858871ff00b787d79c419715afc34 # v2.7.0
