name: Pull Request

on: [ pull_request ]

jobs:
  nix_build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5
        with:
          go-version: '1.24'
      - uses: cachix/install-nix-action@c134e4c9e34bac6cab09cf239815f9339aaaf84e # 31.5.1
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: run nix build
        run: nix build
  lint_and_units:
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5
        with:
          go-version: '1.24'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@55c2c1448f86e01eaae002a5a3a9624417608d84 # 6.5.2
        with:
          version: v1.64
      - name: run lint
        run: ./scripts/runLint.sh
      - name: run unit tests
        run: ./scripts/runUnitTests.sh
  acceptance:
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
      - name: run acceptance tests
        run: ./scripts/runIntegrationAcceptance.sh
  performance:
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
      - name: run performance tests
        run: ./scripts/runIntegrationPerformance.sh
  fault_injection:
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
      - name: run fault injection tests
        run: ./scripts/runIntegrationFaultInjection.sh
  meteor:
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
      - name: run meteor tests
        run: ./scripts/runIntegrationMeteor.sh
  blackbox:
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
      - name: run blackbox tests
        run: ./scripts/runBlackboxTests.sh
